# Generated by Django 5.1 on 2024-08-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorys_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='reting',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DurationField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, choices=[('EN', 'English'), ('RU', 'Russian'), ('UZ', 'Uzbek')], max_length=100)),
                ('reting', models.PositiveBigIntegerField(default=0, verbose_name='#')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.categorys')),
            ],
        ),
    ]
